python main.py --seed 0
python main.py --seed 1
python main.py --seed 2
python main.py --seed 3
python main.py --seed 4
python main.py --seed 5
python main.py --seed 6
python main.py --seed 7
python main.py --seed 8
python main.py --seed 9